### ISSUE TITLE
客户端登录

### ISSUE THREAD

**Issue by skyarea** [wenghengcong/Coderpursue#4]
无法登录呀？登录进去，回到主界面又提示登录

**Comment by wenghengcong** [comment]
@skyarea 

你要确保是真正登录上了，就是在“我”的页面，有用户名和项目等信息。
国内网络针对GitHub访问较慢，登录也很慢，你需要在点击登录按钮后，在GitHub登录的页面等待比较长的时间才能完全登录，中途返回，是会登录失败的。
如果按上面操作还是有问题，希望你能提供更多信息。

**Comment by skyarea** [comment]
登录界面会显示此项目主页，然后回自动跳转到“我”界面，但是显示的还是未登录

**Comment by wenghengcong** [comment]
这是个bug，会在下一版修复。是否登录，现在的判断逻辑是你是否有这个name，这个逻辑下一版会修复。
暂时的解决方案，是你去设置GitHub账户的profile 中的name就可以了。我已经验证过了。
感谢反馈~

**Comment by skyarea** [comment]
嗯，按照您说的试了一下，确实可以了，👍
